# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', '**.cmake']

jobs:
  build:

    strategy:
      fail-fast: false

      matrix:
        platform: [ubuntu-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        lfs: 'true'

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master

    - name: Configure
      run: cmake --preset ${{ matrix.configuration }}

    - name: Build
      run: cmake --build build/${{ matrix.configuration }}

    - name: Test
      run: build/${{ matrix.configuration }}/App -T
