# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build Testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false

      matrix:
        platform: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      # uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure
      run: cmake --preset ${{ matrix.configuration }}

    - name: Build
      run: cmake --build /build/${{ matrix.configuration }}

    - name: Test
      run: /build/${{ matrix.configuration }}/App
