name: Code Linter
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', '**.cmake']
  push:
    branches: [main]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', '**.cmake']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup database
        run: cmake --preset Release

      - name: CPP-Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: build/Release/compile_commands.json
          ignore: 'third-party'
          tidy-checks: '' # Use .clang-tidy config file. 
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
