name: Code Linter
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', '**.cmake']
  push:
    branches: [main]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', '**.cmake']

jobs:
  cpp-linter:
    runs-on: windows-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Setup database
        run: cmake --preset Release

      - name: CPP-Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 18
          extensions: 'h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          files-changed-only: false
          database: build/Release/compile_commands.json
          style: 'file'
          ignore: 'third-party | build'
          verbosity: 'debug'
          tidy-checks: '' 
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
